// marketing-site/app/demo/create-org/page.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { motion } from "framer-motion";
import { Building2, ArrowRight, Loader2 } from "lucide-react";
import Link from "next/link";

export default function CreateOrgPage() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    name: "",
    contact_email: "",
    org_type: "training_institution",
    phone: "",
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      // 1. 获取当前登录用户的 Token (假设已存储在 localStorage)
      const token = localStorage.getItem('access_token');
      if (!token) {
        alert("请先登录！");
        router.push('/demo/login'); // 假设有登录页
        return;
      }

      // 2. 调用后端创建组织接口
      const res = await fetch('http://localhost:8000/organizations/create', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify(formData)
      });

      if (!res.ok) {
        const errorData = await res.json();
        throw new Error(errorData.detail || '创建失败');
      }

      const data = await res.json();
      
      // 3. 存储新的包含 org_id 的 Token
      localStorage.setItem('access_token', data.access_token);
      localStorage.setItem('current_org_id', data.organization_id.toString());

      // 4. 跳转到 Angular 管理后台
      // 假设 Angular 运行在 4200 端口
      window.location.href = `http://localhost:4200/organization/${data.organization_id}/dashboard`;
      
    } catch (error) {
      console.error("创建组织失败:", error);
      const message = error instanceof Error ? error.message : "创建失败，请稍后重试";
      alert(message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-950 flex items-center justify-center p-4">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="w-full max-w-lg bg-slate-900 border border-slate-800 rounded-xl p-8 shadow-2xl"
      >
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-blue-500/10 mb-4">
            <Building2 className="w-8 h-8 text-blue-500" />
          </div>
          <h1 className="text-2xl font-bold text-slate-100">创建您的 STEM 机构</h1>
          <p className="text-slate-400 mt-2">填写基本信息以开启云托管服务</p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          <div>
            <label className="block text-sm font-medium text-slate-300 mb-2">机构名称</label>
            <input
              type="text"
              required
              className="w-full px-4 py-3 bg-slate-950 border border-slate-700 rounded-lg text-slate-100 focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition-all"
              placeholder="例如：星海机器人培训中心"
              value={formData.name}
              onChange={(e) => setFormData({...formData, name: e.target.value})}
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-300 mb-2">联系邮箱</label>
            <input
              type="email"
              required
              className="w-full px-4 py-3 bg-slate-950 border border-slate-700 rounded-lg text-slate-100 focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition-all"
              placeholder="admin@example.com"
              value={formData.contact_email}
              onChange={(e) => setFormData({...formData, contact_email: e.target.value})}
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-300 mb-2">机构类型</label>
            <select
              className="w-full px-4 py-3 bg-slate-950 border border-slate-700 rounded-lg text-slate-100 focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition-all"
              value={formData.org_type}
              onChange={(e) => setFormData({...formData, org_type: e.target.value})}
            >
              <option value="training_institution">STEM 培训机构</option>
              <option value="k12_school">K12 学校科创中心</option>
              <option value="vocational_school">职业学校实训室</option>
              <option value="education_bureau">教育局监管平台</option>
            </select>
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full py-3.5 bg-gradient-to-r from-blue-600 to-blue-500 hover:from-blue-500 hover:to-green-500 text-white font-semibold rounded-lg shadow-lg shadow-blue-500/25 transition-all duration-300 flex items-center justify-center gap-2 disabled:opacity-70 disabled:cursor-not-allowed"
          >
            {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : <>立即创建 <ArrowRight className="w-5 h-5" /></>}
          </button>
        </form>

        <div className="mt-6 text-center text-sm text-slate-500">
          已有账号？ <Link href="/demo" className="text-blue-400 hover:text-blue-300">返回登录</Link>
        </div>
      </motion.div>
    </div>
  );
}

// frontend/src/app/pages/create-org/create-org.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../environments/environment';
import { OrganizationContextService, OrganizationType } from '../../core/services/organization-context.service';

@Component({
  selector: 'app-create-org',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatButtonModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatSnackBarModule
  ],
  template: `
    <div class="create-org-container">
      <mat-card class="create-org-card">
        <mat-card-header>
          <mat-card-title>创建您的 STEM 机构</mat-card-title>
          <mat-card-subtitle>开启智能化管理新篇章</mat-card-subtitle>
        </mat-card-header>
        
        <mat-card-content>
          <form (ngSubmit)="onSubmit()" #orgForm="ngForm">
            <mat-form-field appearance="outline" class="full-width">
              <mat-label>机构名称</mat-label>
              <input matInput [(ngModel)]="formData.name" name="name" required placeholder="例如：未来创客实验室">
            </mat-form-field>

            <mat-form-field appearance="outline" class="full-width">
              <mat-label>联系邮箱</mat-label>
              <input matInput type="email" [(ngModel)]="formData.contact_email" name="contact_email" required placeholder="admin@example.com">
            </mat-form-field>

            <mat-form-field appearance="outline" class="full-width">
              <mat-label>机构类型</mat-label>
              <mat-select [(ngModel)]="formData.org_type" name="org_type" required>
                <mat-option value="training_institution">STEM 培训机构</mat-option>
                <mat-option value="k12_school">K12 学校</mat-option>
                <mat-option value="vocational_school">职业学校</mat-option>
                <mat-option value="education_bureau">教育局/主管部门</mat-option>
              </mat-select>
            </mat-form-field>

            <mat-form-field appearance="outline" class="full-width">
              <mat-label>联系电话 (可选)</mat-label>
              <input matInput [(ngModel)]="formData.phone" name="phone">
            </mat-form-field>

            <mat-form-field appearance="outline" class="full-width">
              <mat-label>地址 (可选)</mat-label>
              <textarea matInput [(ngModel)]="formData.address" name="address" rows="3"></textarea>
            </mat-form-field>

            <button mat-raised-button color="primary" type="submit" [disabled]="!orgForm.form.valid || isLoading" class="full-width submit-btn">
              {{ isLoading ? '正在创建...' : '立即创建' }}
            </button>
          </form>
        </mat-card-content>
      </mat-card>
    </div>
  `,
  styles: [`
    .create-org-container {
      display: flex;
      justify-content: center;
      align-items: center;
      min-height: 100vh;
      background-color: #f5f7fa;
    }
    .create-org-card {
      width: 100%;
      max-width: 500px;
      padding: 20px;
    }
    .full-width {
      width: 100%;
      margin-bottom: 16px;
    }
    .submit-btn {
      margin-top: 20px;
      height: 48px;
      font-size: 16px;
    }
  `]
})
export class CreateOrgComponent {
  formData = {
    name: '',
    contact_email: '',
    org_type: 'training_institution',
    phone: '',
    address: ''
  };
  isLoading = false;

  constructor(
    private http: HttpClient,
    private snackBar: MatSnackBar,
    private router: Router,
    private orgContext: OrganizationContextService
  ) {}

  ngOnInit() {
    // 检查是否已登录，如果没有则跳转到登录页
    const token = localStorage.getItem('access_token');
    if (!token) {
      this.router.navigate(['/login']);
    }
  }

  onSubmit() {
    this.isLoading = true;
    const token = localStorage.getItem('access_token');
    
    this.http.post(`${environment.apiUrl}/api/v1/organizations/create`, this.formData, {
      headers: { Authorization: `Bearer ${token}` }
    }).subscribe({
      next: (res: any) => {
        this.isLoading = false;
        // 保存新的 Token（包含 org_id）
        localStorage.setItem('access_token', res.access_token);
        localStorage.setItem('organization_id', res.organization_id);
        
        // 设置组织上下文
        this.orgContext.setContext({
          id: res.organization_id,
          name: this.formData.name,
          type: this.formData.org_type as OrganizationType
        });
        
        this.snackBar.open('机构创建成功！正在进入管理后台...', '关闭', { duration: 3000 });
        setTimeout(() => {
          this.router.navigate(['/organization', res.organization_id]);
        }, 1000);
      },
      error: (err) => {
        this.isLoading = false;
        const msg = err.error?.detail || '创建失败，请稍后重试';
        this.snackBar.open(msg, '关闭', { panelClass: ['error-snackbar'] });
      }
    });
  }
}
